### ISSUE TITLE
Handle Podfile.lock and Manfiest.lock files when installing links

### ISSUE THREAD

**Issue by mowens** [mowens/cocoapods-links#1]
Currently the `pod link <name>` command will setup links and install dependencies. When installing dependencies the Podfile is unchanged but the Podfile.lock and Manifest.lock files are changed. The Podfile.lock file should not change during linking, however, I think the Manifest.lock file _should_ change. Most people do not check in their Pods directories and if they do they would have to unlink their pods anyways.

So this ticket is to:
1. keep Podfile.lock the same for an linked source before it is linked
2. let Manifest.lock file update normally

**Comment by segiddins** [comment]
@mowens the Podfile.lock and the Manifest.lock must always match

**Comment by mowens** [comment]
@segiddins I have wrote the code that will ignore the links when generating the lock files. Keeping both in sync is easily done but I'm curious of the implication of people who check on their Pods directory

**Comment by mowens** [comment]
This is fixed with the following https://github.com/mowens/cocoapods-links/commit/4dac99b0317119bee8adbb62aaf0cd24c641f938
