### ISSUE TITLE
Link Subspecs

### ISSUE THREAD

**Issue by AnthonyMDev** [mowens/cocoapods-links#2]
It seems that when I am using subspecs, my linked pods do not work.

Is this a known limitation?

Thanks!

**Comment by segiddins** [comment]
@AnthonyMDev can you please be a bit more exact about what exactly you're doing, and how the result is different from what you expect?

**Comment by AnthonyMDev** [comment]
@mowens To give more details here is what is happening.

I have a CocoaPod named `MyPod` with a subspecs `MyPod/Core` and `MyPod/SubSpec1` in its pod spec.

I also have an application project named `MyApp` with this podfile:

```
pod `MyPod/Core`
pod 'MyPod/SubSpec1`
```

This works fine when I am using the pod from my private spec repository. The problem occurs when I try to link to the development pod.

I `pod link` from the pods directory to link the pod. I then `cd` into my project and `pod link MyPod`.

The link seems to work just fine, as the terminal output states that my project is now using the link. But when I open my project, `MyPod` is still in the `Pods` folder, rather than the `Development Pods` folder, and the local version of the pod is not being used.

**Comment by mowens** [comment]
@AnthonyMDev Hey Anthony, sorry for the long delay for a response.

I have pushed changes to make links work with subspecs. Use version 0.2.0 and you should be able to link subspecs correct. Let me know if you have any issues.

**Comment by hfossli** [comment]
How do I install version 0.2.0?

```
╰─$ sudo gem install cocoapods-links 0.2.0
Successfully installed cocoapods-links-0.1.0
Parsing documentation for cocoapods-links-0.1.0
Done installing documentation for cocoapods-links after 0 seconds
ERROR:  Could not find a valid gem '0.2.0' (>= 0) in any repository
```

**Comment by hfossli** [comment]
Got it..

```
╭─hfossli@hfossli-imac-home  ~ ‹1.9.3-p392› 
╰─$ cd Downloads 
╭─hfossli@hfossli-imac-home  ~/Downloads ‹1.9.3-p392› 
╰─$ git clone https://github.com/mowens/cocoapods-links.git
Cloning into 'cocoapods-links'...
cd cocremote: Counting objects: 56, done.
remote: Total 56 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (56/56), done.
Checking connectivity... done
╭─hfossli@hfossli-imac-home  ~/Downloads ‹1.9.3-p392› 
╰─$ cd cocoapods-links
╭─hfossli@hfossli-imac-home  ~/Downloads/cocoapods-links ‹1.9.3-p392› ‹master› 
╰─$ gem build cocoapods_links.gemspec
  Successfully built RubyGem
  Name: cocoapods-links
  Version: 0.2.0
  File: cocoapods-links-0.2.0.gem
╭─hfossli@hfossli-imac-home  ~/Downloads/cocoapods-links ‹1.9.3-p392› ‹master› 
╰─$ sudo gem install cocoapods-links-0.2.0.gem 
Successfully installed cocoapods-links-0.2.0
Parsing documentation for cocoapods-links-0.2.0
Installing ri documentation for cocoapods-links-0.2.0
Done installing documentation for cocoapods-links after 0 seconds
1 gem installed

```

**Comment by hfossli** [comment]
I love Q&A :stuck_out_tongue:

**Comment by mowens** [comment]
@hfossli Looks like I never pushed the latest version to the remote gems repo. It has been pushed now. You can install the latest using the following command:

```
gem install cocoapods-links -v 0.2.0
```

**Comment by hfossli** [comment]
Awesome. Thanks

**Comment by hfossli** [comment]
Great plugin btw! I use it every day on multiple projects

**Comment by mowens** [comment]
@hfossli I'm glad you like it! :smile:
