### ISSUE TITLE
Cocoa pods Version 1.0 beta compatibility

### ISSUE THREAD

**Issue by AnthonyMDev** [mowens/cocoapods-links#4]
Will a version that is compatible with the `1.0` beta be released soon? I need to use the beta now for some bug fixes that aren't in `0.39` but I'd really like to keep using this plugin.

Thanks!

**Comment by mowens** [comment]
1.0 support will be added

**Comment by hfossli** [comment]
Looking forward to this 👍

**Comment by hfossli** [comment]
I could have a go at this, but I don't know how to work on this locally. Can you provide some information about that?

**Comment by cepages** [comment]
+1 to this

**Comment by hfossli** [comment]
See this pull request https://github.com/mowens/cocoapods-links/pull/5

**Comment by cepages** [comment]
So does that mean that we can create a new version which works with Cocoa Pods 1.0? 

And also close this issue? 

![](http://i.giphy.com/DKnMqdm9i980E.gif)

**Comment by mowens** [comment]
Released and closed 👍
